<?php

namespace aigletter\logging\infrastructure\commands;

class MigrateController extends \yii\console\controllers\MigrateController
{
    public function actionUp($limit = 0)
    {
        return parent::actionUp($limit); // TODO: Change the autogenerated stub
    }
}